# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '小兰魔法书' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 小兰魔法书

  target '小兰魔法书UITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod ‘Masonry’
pod ‘AFNetworking’
pod ‘SDWebImage’
pod ‘YYModel’
pod ’MJRefresh’
pod ‘SVProgressHUD’
end
